### PR TITLE
fix(doc): Transform Processor CDI Decorator into manual decorators

### LINKED ISSUE #117: Random startup failures with Processor Decorator and ConfigurationCustomizer
This impacts only Quarkus versions 3.8.x to 3.10.x, prior versions down to Quarkus 3.2 were not tested, but Quarkus 3.2 LTS does not present the problem.

A reproducer is provided.

[reproducer-injection-generics.zip](https://github.com/user-attachments/files/17292716/reproducer-injection-generics.zip)

The issue happens if:

* one defines a `ConfigurationCustomizer` to inject a custom serde
* one defines a custom Processor decorator using CDI's Decorator annotation

### PR DESCRIPTION
**Pull request by edeweerd1A**
We noticed flackiness with QuarkusTest and usage of `Processor` decorators. It is generating randomly ClassNotFoundException.
It is happening only with Quarkus 3.8 LTS, recent versions like 3.15 or older like 3.2 do not present the issue.

The solution found is a fallback of sorts, by removing the usage of @Decorator in the processor decorators. Instead they are transformed in old-school, composition-design-pattern-inspired beans with a lombok delegate. The generic type signature is removed so they can be transformed in Dependent beans. Why's that? 1. A class with generics cannot be a bean, according to compilation errors, and 2. processors returned by the supplier need to be new instances everytime. Priorities are kept, and used to resolve in order the beans, for a manual encapsulation achieved with a for loop on the list of beans.

And with that, the flackiness is gone.

Of course, those changes will not be propagated to main and the future 3.15 branch, where this flackiness is not an issue, AND the usage of CDI's Decorator can be kept.

The documentation is updated accordingly.

Fixes #117

### CODE REVIEW

**Comment by edeweerd1A** [comment]
Migration guide written in wiki: https://github.com/quarkiverse/quarkus-kafka-streams-processor/wiki/quarkus%E2%80%90kafka%E2%80%90streams%E2%80%90processor-2.0-migration-guide

File: api/src/main/java/io/quarkiverse/kafkastreamsprocessor/api/decorator/processor/AbstractProcessorDecorator.java
Comment (rquinio1A) [inline api/src/main/java/io/quarkiverse/kafkastreamsprocessor/api/decorator/processor/AbstractProcessorDecorator.java:1]: Does this need to be in the api module or it could stay in the impl ?
I see integration-tests new HeaderDecorator compiling on it, but not sure if it's a new capability or not.

File: api/src/main/java/io/quarkiverse/kafkastreamsprocessor/api/decorator/processor/AbstractProcessorDecorator.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+ */
+package io.quarkiverse.kafkastreamsprocessor.api.decorator.processor;
+
+import org.apache.kafka.streams.processor.api.Processor;
+
+import lombok.Getter;
+import lombok.Setter;
+import lombok.experimental.Delegate;
+
+public class AbstractProcessorDecorator implements Processor {
```
Comment (rquinio1A) [inline api/src/main/java/io/quarkiverse/kafkastreamsprocessor/api/decorator/processor/AbstractProcessorDecorator.java:28]: Class should be flagged as deprecated, if it's removed in RHBQ 3.15 ?

File: docs/modules/ROOT/pages/index.adoc [hunk 2]
```diff
@@ -759,23 +762,52 @@ The priority is to be set based on the priorities of the existing decorators whi
...
+Such a decorator will automatically been taken into account by CDI.
 The priority will control at which point your decorator will be called among all other decorators.
 
+[CAUTION]
+====
+We noticed with a new integration-test that is using a custom serde, that usage of custom CDI `Decorator` is causing microservices to randomly crash at startup.
+This happens for specific versions of Quarkus.
+Known impacted versions are 3.8.x, 3.9.x and 3.10.x.
+The 3.2 LTS and upcoming 3.15 LTS versions do not suffer from this symptom.
+The **only** solution found was to remove usage of `@Decorator` for `Processor` decorators for microservices based on Quarkus 3.8 LTS.
```
Comment (rquinio1A) [inline docs/modules/ROOT/pages/index.adoc:801]: We could mention if/until https://github.com/quarkusio/quarkus/pull/43245 is backported to 3.8 LTS ?

File: api/src/main/java/io/quarkiverse/kafkastreamsprocessor/api/decorator/processor/AbstractProcessorDecorator.java
Comment (edeweerd1A) [reply api/src/main/java/io/quarkiverse/kafkastreamsprocessor/api/decorator/processor/AbstractProcessorDecorator.java:1]: it needs yeah, cause that type is used when discovering the beans

File: docs/modules/ROOT/pages/index.adoc (hunk 2 above)
Comment (edeweerd1A) [reply docs/modules/ROOT/pages/index.adoc:801]: Changed the link to https://github.com/quarkusio/quarkus/pull/41258 will seems more the origin of the "fix" in quarkus 3.11

File: api/src/main/java/io/quarkiverse/kafkastreamsprocessor/api/decorator/processor/AbstractProcessorDecorator.java (hunk 1 above)
Comment (edeweerd1A) [reply api/src/main/java/io/quarkiverse/kafkastreamsprocessor/api/decorator/processor/AbstractProcessorDecorator.java]: done

File: api/src/main/java/io/quarkiverse/kafkastreamsprocessor/api/decorator/processor/AbstractProcessorDecorator.java [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+ * </p>
+ * <p>
+ * Class introduced in 2.0, for compatibility with Quarkus 3.8 random failure to start when using custom processor
+ * decorators.
+ * </p>
+ *
+ * @deprecated It will be removed in 3.0, with the integration of Quarkus 3.15 where we will be able to go back to pure
+ *             CDI decorators.
+ */
+@Deprecated(forRemoval = true, since = "2.0")
```
Comment (vietk) [inline api/src/main/java/io/quarkiverse/kafkastreamsprocessor/api/decorator/processor/AbstractProcessorDecorator.java:46]: Just born and already obsolete :D

File: impl/src/main/java/io/quarkiverse/kafkastreamsprocessor/impl/KStreamProcessorSupplier.java [hunk 4]
```diff
@@ -76,17 +80,20 @@ public class KStreamProcessorSupplier<KIn, VIn, KOut, VOut> implements Processor
...
             Instance<org.apache.kafka.streams.processor.Processor<?, ?>> beanInstances,
-            Instance<Kafka2ProcessorAdapter<?, ?>> adapterInstances, BeanManager beanManager) {
+            Instance<Kafka2ProcessorAdapter<?, ?>> adapterInstances, BeanManager beanManager,
+            Instance<AbstractProcessorDecorator> processorDecorators) {
         this.kafka3BeanInstances = kafka3BeanInstances;
         this.beanInstances = beanInstances;
         this.adapterInstances = adapterInstances;
+        this.processorDecorators = processorDecorators;
+
+        List<String> processorDecoratorNames = new ArrayList<>(processorDecorators.stream()
```
Comment (vietk) [inline impl/src/main/java/io/quarkiverse/kafkastreamsprocessor/impl/KStreamProcessorSupplier.java:90]: how the list of processorDecorators is now ordered?  I can't find documentation on that

File: impl/src/main/resources/META-INF/microprofile-config.properties [hunk 5]
```diff
@@ -19,3 +19,6 @@ kafka-streams.internal.leave.group.on.close=true
 # Deactivate exposure of metrics through JMX beans
 # It is still adding a mxBean in AppInfoParser though
 kafka-streams.auto.include.jmx.reporter=false
+# For compatibility with generic decorators and Quarkus versions prior to 3.11.0
+# TODO: remove in main branch as the problem is not reproducible with Quarkus 3.11.0 and later versions
+quarkus.test.flat-class-path=true
```
Comment (vietk) [inline impl/src/main/resources/META-INF/microprofile-config.properties:24]: do you need this property since you have switched to bean injection?

Comment (edeweerd1A) [reply impl/src/main/resources/META-INF/microprofile-config.properties]: removed

**Review by vietk — APPROVED** [review]
